### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by teeparham**
* Update the development dependency on minitest so we can test against Rails 4.2
* Update to the latest octokit (~> 4.0)

### CODE REVIEW

**Comment by bcardarella** [comment]
@teeparham we're not using Ruby anymore. Do you want commit/rubygems access?

**Comment by teeparham** [comment]
@bcardarella interesting... Sure, we're using this gem, so I can do maintenance & releases.

**Comment by bcardarella** [comment]
@teeparham this failed for Ruby 2.0.0 & 1.9.3

**Comment by teeparham** [comment]
It's not related to the ruby version - there are intermittent test failures with that (& some other) tests. I can take a look later.

**Comment by JuanitoFatas** [comment]
@teeparham octokit has been upgraded https://github.com/dockyard/party_foul/pull/120.

**Pull request closed without merging**
